### PR TITLE
Track injections in the imploder.

### PR DESCRIPTION
**Pull request by hendrikvanantwerpen**
I would like to track injections in the parser, and record those in the
ImploderAttachment, so that I might make them explicit later without having to
rewrite the grammar itself.

I've made a first attempt, but I'm not sure I got exactly the right place to do
it. There are also a bunch of cases that I'm not sure how to handle:

- Should lexical sorts be in the injection list? E.g., `Id = ID`
- Should tuples be included (and how to present that)? E.g., `Pair = <(<Term>, <Term>)>`
- Should list be included (and how to present that)? E.g., `Terms = {Term ", "}*`

Feedback on this from people that know more about the parser is appreciated.

### CODE REVIEW

**Comment by jasperdenkers** [comment]
I assume you mean an injection from error recovery. In that case your current implementation tracks too many sorts/productions. Looking at the following part of the (JSGLR2) imploder: 

https://github.com/metaborg/jsglr/blob/4d7870bb4673ce99d614b30cf5ad610c8681bd33/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/imploder/TokenizedTreeImploder.java#L200-L214

You added the tracking at the branch on line 210/211. This branch is for all productions without a constructor and with a single non-terminal on the right-hand side. You could add a filter to perform the tracking for injection productions only. That would require an extra attribute in `IProduction`.

**Comment by hendrikvanantwerpen** [comment]
@jasperdenkers Thanks for the info. I'm precisely interested in all constructor-less productions (I call those injections). However, I think I'd want to filter out lexical sorts there. Do you know if I can figure that out at that point?

**Comment by jasperdenkers** [comment]
Yes, for the filter you can use: https://github.com/metaborg/sdf/blob/master/org.metaborg.tableinterfaces/src/main/java/org/metaborg/parsetable/IProduction.java#L29.

**Comment by mpsijm** [comment]
Since the tracking at the branch on line 210/211 happens inside the method `createContextFreeTerm`, isn't it the case that injections are only created for context-free constructor-less productions anyway? Lexical sorts should not even end up here, as `createContextFreeTerm` is not called on terms that have lexical productions.

**Comment by jasperdenkers** [comment]
Ah, right, that is correct. Then the filter is not needed.

**Comment by hendrikvanantwerpen** [comment]
@jasperdenkers @mpsijm Can you do a review of these changes to see if they can be  merged?

Changes:
* Add a list of injections to `ImploderAttachment`.
* Add `createInjection` indirection to `ITreeFactory` to be able to act on injections.
* Push sort to injection list in `TermTreeFactory` (both `jsglr` and `jsglr2`)
* Add `Injections` utility class with a method to explicate injections to constructors. The naming of the injection constructors is controlled by a user-provided function. The PR https://github.com/metaborg/spoofax/pull/48 adds a primitive that allows you to do this from Stratego.

Tested:
* On the Java grammar using jsglr and jsglr2.

Interesting details:
* Lexical productions seem to go through `createInjection`. To prevent `ID2ID` injections or things like that, I check that the two sorts are different.

**Pull request merged**
