### PR TITLE
Stratego code that parses unambiguous with JSGLR1 but not with JSGLR2

### PR DESCRIPTION
**Pull request by Apanatshka**
**Note that the added tests currently fail!**
I've added the Stratego parse table and a test file with some code that's problematic for JSGLR2. JSGLR1 manages to parse it unambiguously, I used it to produce the `sampleProgram.ast` file. 

The Stratego code is of the form `x@[]`, and JSGLR2 thinks there's an ambiguity between `Term` and `PreTerm` ([relevant](https://github.com/metaborg/strategoxt/blob/f3e6e2f69d90a940739e77ace32c7ace8c183069/strategoxt/syntax/stratego-front/syn/Stratego-Core-Terms.sdf#L30-L33) [productions](https://github.com/metaborg/strategoxt/blob/f3e6e2f69d90a940739e77ace32c7ace8c183069/strategoxt/syntax/stratego-front/syn/Stratego-Sugar-Terms.sdf#L19-L20)) despite the `prefer` on the `Term` version of the `As` pattern.

### CODE REVIEW

**Comment by jasperdenkers** [comment]
Isolated the problem with the following (trimmed) SDF grammar:

```
definition
module stratego
exports

  sorts Var Term PreTerm

  context-free start-symbols
    Start
  
  context-free syntax
    Term -> Start
    
    "x"      -> Var  {cons("Var")}
    
    Var      -> Term {prefer}
    Var      -> PreTerm
    
    PreTerm -> Term {cons("NoAnnoList")}
    
    Var "@" Term        -> Term {cons("As"),prefer}
    Var "@" PreTerm     -> PreTerm {cons("As")}
    "[" {Term ","}* "]" -> PreTerm {cons("List")}
    
    Term "#" "(" Term ")"    -> PreTerm {cons("Explode")}

  context-free priorities
    Term "#" "(" Term ")" -> PreTerm {cons("Explode")} >
    Var "@" Term -> Term {cons("As")}
```

For input `x@[]`:

 - JSGLR1:

```
As(Var(), NoAnnoList(List([])))
```

 - JSGLR2:

```
amb(
  [ NoAnnoList(As(Var(), List([])))
  , As(Var(), NoAnnoList(List([])))
  ]
)
```

When removing the priorities from the grammar, JSGLR2 parses non-ambiguously like JSGLR1.

Somehow, adding the priorities alter the parse table in such a way that JSGLR2 parses ambiguously.

Same pattern in a more abstract grammar:

```
definition
module stratego
exports
  sorts A B

  context-free start-symbols
    Start
  
  context-free syntax
    A -> Start

    B -> A {cons("Inject")}
    
   "P" A  -> A {cons("PA"),prefer}
   "P" B  -> B {cons("PB")}
    A "P" -> A {cons("AP")}
    
   "x" -> B {cons("X")}

  context-free priorities
    A "P" -> A {cons("AP")}
 > "P" A  -> A {cons("PA"),prefer}
```

For input `Px`:

 - JSGLR1:

```
PA(Inject(X()))
```

 - JSGLR2:

```
amb([
  PA(Inject(X())),
  Inject(PB(X()))
])
```

Again, when removing the priorities, JSGLR2 parses non-ambiguously like JSGLR1.

**Comment by jasperdenkers** [comment]
Parse tables for the abstract grammar (created with `sdf2table -i /path/to/grammar.def -m stratego -t | pp-aterm -o {with, without}-prios.txt`):
 - [with-prios.txt](https://github.com/metaborg/jsglr/files/3285935/with-prios.txt)
 - [without-prios.txt](https://github.com/metaborg/jsglr/files/3285936/without-prios.txt)

**Comment by jasperdenkers** [comment]
Parse forest and stack visualized via the new JSGLR2 CLI (https://github.com/metaborg/jsglr/tree/develop/jsglr2/org.spoofax.jsglr2.cli, not yet in master):

**Without priorities**
Parse forest:
without-prios-parseforest
Stack:
without-prios-stack

**With priorities**
Parse forest:
with-prios-ParseForest
Stack:
with-prios-stack

**Comment by jasperdenkers** [comment]
Closing since bug seems to be in the old `sdf2table` parser generation implementation.

**Comment by Apanatshka** [comment]
Today we found that the priority that messes up the C version of sdf2table also influences where `amb` nodes end up. So we get this out of JSGLR2 with the C version of sdf2table:

```
Match(
  Anno(
    Op(
      ""
    , [ amb(
          [ [ As(
                Var("c")
              , Anno(
                  Op("Call", [Var("s"), Var("s1")])
                , Wld()
                )
              )
            ]
          , [ Anno(
                As(
                  Var("c")
                , Op("Call", [Var("s"), Var("s1")])
                )
              , Wld()
              )
            ]
          ]
        )
      , Anno(
          Op(
            "FunTType"
          , [Var("st"), Var("tt"), Var("t1"), Var("t2")]
          )
        , Wld()
        )
      ]
    )
  , Wld()
  )
)
```

Instead of the correct (given by JSGLR1, and by JSGLR2 when using the Java version of sdf2table):

```
Match(
  Anno(
    Op(
      ""
    , [ amb(
          [ As(
              Var("c")
            , Anno(
                Op("Call", [Var("s"), Var("s1")])
              , Wld()
              )
            )
          , Anno(
              As(
                Var("c")
              , Op("Call", [Var("s"), Var("s1")])
              )
            , Wld()
            )
          ]
        )
      , Anno(
          Op(
            "FunTType"
          , [Var("st"), Var("tt"), Var("t1"), Var("t2")]
          )
        , Wld()
        )
      ]
    )
  , Wld()
  )
)
```

**Pull request closed without merging**
