### PR TITLE
Feature: layout constraints evaluation and added tests

### PR DESCRIPTION
**Pull request by Olavhaasie**
In this PR I have updated the evaluation of layout constraints to reflect the changes made in https://github.com/metaborg/sdf/pull/54. Instead of returning an `Optional<Boolean>` from `evaluate`, it now returns just `bool`, which is `false` when the constraint does not hold. Furthermore, I have split up the evaluate into more separate functions.
Finally, I have added more layout disambiguation tests, which should better cover the features of layout sensitive parsing.

_This code only compiles and has passing tests when used with the [`develop/layout-constraints`](https://github.com/metaborg/sdf/tree/develop/layout-constraints) branch on metaborg/sdf, which is not yet merged with master._

### CODE REVIEW

**Comment by jasperdenkers** [comment]
Nice 👍 

Could you also factor out the optionals in e.g. `evaluateBoolean `, `evaluateComparison`, `evaluateExpression`, `evaluateTreeRef`? It seems to me that implicitly falling back to evaluating to `true` (see e.g. https://github.com/metaborg/jsglr/pull/101/files#diff-a6de409b7c805f0ebe6b91f275af5326c0eae7d5bfb8f5dba404007842cd0a81R57) is undesirable. I guess such cases could be prevented by static analysis on SDF? Or am I missing something?

**Comment by Olavhaasie** [comment]
`Optional.empty()` is being used to _ignore_ the position of the tree, it will go upwards the constraint and finally ignoring it by returning `true`. There are 4 cases were it is being used.

The first case is when the `left` or `right` position do not exist. I think these can be changed to exceptions, since those should not occur.
https://github.com/metaborg/jsglr/blob/ca1dfc3ebf8241c3f6c25b29c39fbf1258f1f3bb/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutConstraintEvaluator.java#L123-L124

The second case is when a given tree is not a `ILayoutSensitiveParseNode` when taking the left or right position. Other options are `ILayoutSensitiveCharacterNode` or `ICompositeParseForest`. However, I have no idea how they are constructed and if they should occur in this phase.
https://github.com/metaborg/jsglr/blob/ca1dfc3ebf8241c3f6c25b29c39fbf1258f1f3bb/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutConstraintEvaluator.java#L119-L121

The third case is when a tree has `isIgnoreLayoutConstraint()` 
https://github.com/metaborg/jsglr/blob/ca1dfc3ebf8241c3f6c25b29c39fbf1258f1f3bb/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutConstraintEvaluator.java#L101-L104
 I don't actually know what that means in SDF, is it the `ignore-layout` attribute? If so it could be rejected in static analysis.

Finally, I think returning `Optional.empty()` when the tree is empty is the only option, since it cannot be prevented and we don't want the tree to be rejected because of some invisible tree.
https://github.com/metaborg/jsglr/blob/ca1dfc3ebf8241c3f6c25b29c39fbf1258f1f3bb/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutConstraintEvaluator.java#L106-L108

So, to answer your question I don't think it is possible to remove the `Optional`.

**Comment by jasperdenkers** [comment]
> The second case is when a given tree is not a `ILayoutSensitiveParseNode` when taking the left or right position. Other options are `ILayoutSensitiveCharacterNode` or `ICompositeParseForest`. However, I have no idea how they are constructed and if they should occur in this phase.

You can assume that the tree is a `ILayoutSensitiveParseNode` here. `ILayoutSensitiveCharacterNode`s should not occur here and the composite parse forest has a parse node that extends the `ILayoutSensitiveParseNode`.

> The third case is when a tree has `isIgnoreLayoutConstraint()`
> I don't actually know what that means in SDF, is it the `ignore-layout` attribute? If so it could be rejected in static analysis.

It's indeed the `ignore-layout` attribute. @udesou do you know what the idea behind this attribute is?

Maybe it is meant to ignore certain parse nodes in determining the "shape" of parse nodes? See:

https://github.com/metaborg/jsglr/blob/ca1dfc3ebf8241c3f6c25b29c39fbf1258f1f3bb/org.spoofax.jsglr2/src/main/java/org/spoofax/jsglr2/layoutsensitive/LayoutSensitiveParseForestManager.java#L93

> Finally, I think returning `Optional.empty()` when the tree is empty is the only option, since it cannot be prevented and we don't want the tree to be rejected because of some invisible tree.

Could you explain why that case cannot be prevented? Would this occur e.g. when using a tree selector for an optional subtree which could be empty? To me it seems confusing that in such cases the constraint would simply evaluate to true.

**Comment by Olavhaasie** [comment]
> Could you explain why that case cannot be prevented? Would this occur e.g. when using a tree selector for an optional subtree which could be empty? To me it seems confusing that in such cases the constraint would simply evaluate to true.

An example I could think of:
```
context-free syntax
  A.A = "a" b:B? {layout(align "a" b)}
  B.B = "b"
```
If I write `a` here then `B` is empty and then it would make no sense to have `B` align with `a`, so it can be safely ignored. If we do not ignore it then we have the possibility where `a` is being rejected because an invisible constructor is not aligned. There would be no way to fix it since there is nothing that can be moved to align with `a`. However, it must not be ignored when `B` is not empty. This occurrence cannot be prevented at static analysis, since `B` may be some or none. Perhaps there is another way of detecting whether a tree is empty? I have made a new commit which adds tests for these cases.

**Comment by jasperdenkers** [comment]
I'm not sure if that occurs or should occur in practice, but for now I understand it needs the optionals in the implementation and thus I'm fine with merging this PR.

**Comment by udesou** [comment]
So, the `ignore-layout` constraint exists to ignore constraints locally. For instance, inside a block with explicit delimiters such as `{` and `}`. See the original paper in https://www.informatik.uni-marburg.de/~seba/publications/layout-parsing.pdf.

Just one thing before merging this. I don't understand:

> The first case is when the left or right position do not exist. I think these can be changed to exceptions, since those should not occur.

In fact this occurs quite often: `left` and `right` do not exist for (sub)trees that only span a single line. That also follows from the initial definition in the paper.

**Comment by udesou** [comment]
Note that applying for example, the offside rule (or a constraint that compares `left` or `right`) to a single line tree/sentence should always mean that the constraint has been evaluated to true. The same goes for `ignore-layout`.

**Comment by Olavhaasie** [comment]
Thanks for your answer. I understand now that it should not be changed :+1:

**Review by udesou — APPROVED** [review]

**Comment by udesou** [comment]
@jasperdenkers If you can build Spoofax and run it, can you maybe have a quick look? Otherwise, the files look fine to me (here and in SDF) and you can merge it. I wanted to try it out, but I can't seem to make a freshly built Spoofax run on my machine.

**Comment by jasperdenkers** [comment]
@udesou will do next week.

**Pull request merged**
